disable streaming by default + fix problem:
libmpconf/libmpconf.a(m_option.o): In function `parse_custom_url(m_option const*, char const*, char*, void*, int)':
m_option.cpp:(.text+0x23e8): undefined reference to `mpxp::url2string(char*, char const*)'
collect2: ld returned 1 exit status

P.S.: In addition to [438] comments i need to say that illegal patch violates
      GPL because doesn't exists in form of source code available for receiving
      and modifications.

Preamble ( GPLv2 ):

  When we speak of free software, we are referring to freedom, not
price.  Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
this service if you wish), that you receive source code or can get it
if you want it, that you can change the software or use pieces of it
in new free programs; and that you know you can do these things.

TERMS AND CONDITIONS (GPLv3) :

  1. Source Code.

  The "source code" for a work means the preferred form of the work
for making modifications to it.  "Object code" means any non-source
form of a work.